# Generated by Django 5.0.1 on 2024-01-26 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="color",
            field=models.TextField(default="No se introdujeron colores."),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="description",
            field=models.TextField(default="Sin descripción."),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="product_dimensions",
            field=models.TextField(default="No se introdujeron dimensiones."),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
