# Generated by Django 5.0.1 on 2024-01-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ecommerce",
            "0002_productmodel_color_productmodel_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="color",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="product_dimensions",
            field=models.TextField(),
        ),
    ]
