# Generated by Django 5.0.1 on 2024-02-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0003_alter_productmodel_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="state",
            field=models.CharField(
                choices=[
                    ("BR", "BORRADOR"),
                    ("PU", "PUBLICADO"),
                    ("PR", "PRIVADO"),
                ],
                default="BR",
                max_length=2,
            ),
        ),
    ]
