# Generated by Django 5.0.1 on 2024-03-10 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0005_alter_productmodel_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmodel",
            options={"ordering": ["-updated", "-timestamp"]},
        ),
        migrations.AddField(
            model_name="productmodel",
            name="publish_timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
