# Generated by Django 5.0.1 on 2024-03-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0006_alter_productmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="color",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
