# Generated by Django 5.0.1 on 2024-03-12 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ecommerce",
            "0007_productmodel_slug_alter_productmodel_color_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="product_dimensions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
